runtime: python312

instance_class: F2

resources:
  memory_gb: 2

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /help
  static_dir: help

- url: /js
  static_dir: js

- url: /layouts
  static_dir: layouts

